### ISSUE TITLE
"ValueError: zero length field name in format" in _escape_value() under Python 2.6

### ISSUE THREAD

**Issue by phalenor** [influxdata/influxdb-python#288]
I know Python 2.6 isn't officially supported, but please consider the fact that many of us are stuck running CentOS 6.x or equivalent and don't have access to python 2.7. I haven't looked into this too much, but it might be as simple as changing all of the .format's to use numbered format strings to be backwards compatible with 2.6. The usage of .format() is inconsistent at the least just glancing at the code. I would much rather not write my own influxdb http client for what is, so far, a very simple script (taking Nagios perfdata and dumping it into influxdb).

Thanks!

```
January 26 23:30:35 fluxios.py[15279] ERROR (loop) Caught exception in loop()
Traceback (most recent call last):
  File "fluxios.py", line 386, in loop
    process_spool_dir(cfg['fluxios']['spool_directory'])
  File "fluxios.py", line 328, in process_spool_dir
    if send_points(points):
  File "fluxios.py", line 343, in send_points
    batch_size=int(cfg['fluxios']['batch_size'])
  File "/usr/lib/python2.6/site-packages/influxdb/client.py", line 384, in write_points
    tags=tags)
  File "/usr/lib/python2.6/site-packages/influxdb/client.py", line 436, in _write_points
    expected_response_code=204
  File "/usr/lib/python2.6/site-packages/influxdb/client.py", line 276, in write
    data=make_lines(data, precision).encode('utf-8'),
  File "/usr/lib/python2.6/site-packages/influxdb/line_protocol.py", line 119, in make_lines
    value = _escape_value(point['fields'][field_key])
  File "/usr/lib/python2.6/site-packages/influxdb/line_protocol.py", line 59, in _escape_value
    "\n", "\\n"
ValueError: zero length field name in format
```

**Comment by aviau** [comment]
I don't mind supporting python2.6. Someone would have to fix 2.6 support himself and open a PR. I'll gladly enable python2.6 tests too so that we don't make backwards incompatible changes.
