### ISSUE TITLE
influxdb.client.InfluxDBClientError: 404: 404 page not found

### ISSUE THREAD

**Issue by KyleMHB** [influxdata/influxdb-python#382]
Using:
Influx 1.0.2
Python 2.7

Result:
```
[{'fields': {'moisture_raw': '987', 'moisture_adj': '970', 'moisture': '0'}, 'tags': {'test': 'TRUE', 'pot': '0'}, 'measurement': 'moisture_readings'}]
Exiting
Traceback (most recent call last):
  File "/home/pi/Scripts/Planty/RPi3/planty_listner.py", line 50, in <module>
    main()
  File "/home/pi/Scripts/Planty/RPi3/planty_listner.py", line 45, in main
    mqttc.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1378, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 897, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1177, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1766, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2239, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2414, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2574, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/pi/Scripts/Planty/RPi3/planty_listner.py", line 35, in on_message
    client.write_points(json_body)
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 170, in write_points
    return self.write_points_with_precision(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 194, in write_points_with_precision
    status_code=200
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 124, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.client.InfluxDBClientError: 404: 404 page not found
```

Python code:
```
def on_message(client, userdata, msg):
    raw_message = str.split(msg.payload,':')
    data = {}
    data['pot'] = raw_message[0]
    data['moisture_raw'] = raw_message[1]
    data['moisture_adj'] = raw_message[2]
    data['moisture'] = raw_message[3]
    json_body = [
        {
            "measurement": "moisture_readings",
            "tags": {
                "pot": data['pot'],
                "test": "TRUE"
                },
            "fields": {
                "moisture_raw": data['moisture_raw'],
                "moisture_adj": data['moisture_adj'],
                "moisture": data['moisture']
            }
        }
    ]
    print json_body
    client = InfluxDBClient('127.0.0.1', 8086, 'root', 'root', 'Planty')
    client.write_points(json_body)
```

DB does exist:
```
> show databases
name: databases
---------------
name
_internal
Planty
```

**Comment by KyleMHB** [comment]
Found the problem and solution:
http://stackoverflow.com/a/36952335/2842831

I needed to run the pip commands as sudo.
