### ISSUE TITLE
influxdb.client.InfluxDBClientError: 404: 404 page not found

### ISSUE THREAD

**Issue by CaptainKey** [influxdata/influxdb-python#448]
Hi,

I have some troubles with influxdb-client.
Indeed i used the python example : tutorial.py
BUT i have this error !
What do you think about it ? 

`Create database: example
Traceback (most recent call last):
  File "tutorial.py", line 68, in <module>
    main(host=args.host, port=args.port)
  File "tutorial.py", line 33, in main
    client.create_database(dbname)
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 318, in create_database
    status_code=201
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 124, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.client.InfluxDBClientError: 404: 404 page not found`

influxdb-python | version :  0.1.12-1
Linux Distrib : Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

**Comment by CaptainKey** [comment]
PROBLEM SOLVE !
I install influxdb-python with pip command ! It seems that it is better to install influxdb-python with pip than apt-get !
