### ISSUE TITLE
Issue writing pandas DataFrame to influxDB

### ISSUE THREAD

**Issue by martinbel** [influxdata/influxdb-python#460]
Hi, 

I'm trying to insert a simple DataFrame to influxDB and I'm having some issues making it work. 
I have a very simple DataFrame with an index of class: `DatetimeIndex`. I'm using the following Python version 2.7.13 |Anaconda 4.3.1 (64-bit). 

```
>>> df = df.set_index(['time'])
>>> df.head()
                         emg  ecg
time                             
1970-01-02 09:50:58.000    0    0
1970-01-02 09:50:58.005    0    0
1970-01-02 09:50:58.010    0    0
1970-01-02 09:50:58.015    0    0
1970-01-02 09:50:58.020    0    0
>>> df.dtypes
emg    int64
ecg    int64
dtype: object
>>> df.inde     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/avisdev/anaconda2/envs/venv_name/lib/python2.7/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'inde'
>>> df.index
DatetimeIndex([       '1970-01-02 09:50:58', '1970-01-02 09:50:58.005000',
               '1970-01-02 09:50:58.010000', '1970-01-02 09:50:58.015000',
               '1970-01-02 09:50:58.020000', '1970-01-02 09:50:58.025000',
               '1970-01-02 09:50:58.030000', '1970-01-02 09:50:58.035000',
               '1970-01-02 09:50:58.040000', '1970-01-02 09:50:58.045000',
               ...
               '1970-01-02 09:50:58.950000', '1970-01-02 09:50:58.955000',
               '1970-01-02 09:50:58.960000', '1970-01-02 09:50:58.965000',
               '1970-01-02 09:50:58.970000', '1970-01-02 09:50:58.975000',
               '1970-01-02 09:50:58.980000', '1970-01-02 09:50:58.985000',
               '1970-01-02 09:50:58.990000', '1970-01-02 09:50:58.995000'],
              dtype='datetime64[ns]', name=u'time', length=200, freq=None)
>>> protocol = 'json'
>>> dbname='data'
>>> client = DataFrameClient(host='localhost', port=8086, database=dbname)
>>> client.write_points(df, measurement='emg_ecg', database=dbname)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/avisdev/anaconda2/envs/venv_name/lib/python2.7/site-packages/influxdb/_dataframe_client.py", line 117, in write_points
    numeric_precision=numeric_precision)
  File "/home/avisdev/anaconda2/envs/venv_name/lib/python2.7/site-packages/influxdb/_dataframe_client.py", line 237, in _convert_dataframe_to_lines
    if not (isinstance(dataframe.index, pd.tseries.period.PeriodIndex) or
AttributeError: 'module' object has no attribute 'period'
```

It seems the issue is a package dependency, but I do have the latest pandas version installed. 

```
>>> pd.__version__
u'0.20.1'
```

Any ideas how to sort this out?

**Comment by aviau** [comment]
fixed in a2ac2e8118c9220419eaf483685eeda491335612

**Comment by martinbel** [comment]
I've installed the package today, and it's not working.

**Comment by aviau** [comment]
Did you install from master? This commit is not available in any release.

**Comment by martinbel** [comment]
I've installed it as it's described in the readme. 
```
pip install influxdb
```

**Comment by aviau** [comment]
As I just said, this commit is not yet available in any release, so installing it from pypi is not enough.

**Comment by aviau** [comment]
I have just created a new tag and uploaded it to pypi for you. influxdb==4.1.1

**Comment by martinbel** [comment]
thanks! that's awesome!

**Comment by aviau** [comment]
<3
