### ISSUE TITLE
Can Not Query a Large Set of Data

### ISSUE THREAD

**Issue by xanderdunn** [influxdata/influxdb-python#463]
I'm using a Megawat-1 InfluxCloud instance with InfluxDB 1.2.3.  That's 64GB storage with 8GB RAM.

Here is my query:
```
    client = DataFrameClient(host=host, port=8086, username=user, password=password, ssl=True, verify_ssl=True)
    historical_data = client.query("SELECT * FROM my_measurement;", database="processed", chunked=True)
```

This gives the error:
```
Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 535, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 590, in read_chunked
    self._update_chunk_length()
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 539, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/models.py", line 703, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 428, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 618, in read_chunked
    self._original_response.close()
  File "/Users/admin/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 184, in <module>
    main()
  File "./main.py", line 107, in main
    historical_data = db.query("SELECT * FROM my_measurement;", database="processed", chunked=True)
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/influxdb/_dataframe_client.py", line 142, in query
    results = super(DataFrameClient, self).query(query, database=database)
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/influxdb/client.py", line 381, in query
    expected_response_code=expected_response_code
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/influxdb/client.py", line 247, in request
    timeout=self._timeout
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/admin/anaconda3/lib/python3.5/site-packages/requests/models.py", line 706, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

Executing the same query in the influx shell fails with error:
```
> SELECT COUNT(*) FROM my_measurement
ERR:
```

I suspect it's because I'm requesting too much information.

Executing this:
```
influx -host $INFLUX_HOST -port 8086 -username USER -password PASSWORD -ssl -database "processed" -execute "show series" > dbseries.txt; cat dbseries.txt | wc -l
```
shows that the series cardinality of the database `processed` is 5483.  There are about 150,000 points.  There are 38 fields.  When stored in plain text in a .csv, it's 41MB of data.  

If I use the `InfluxDBClient` instead of `DataFrameClient` so that I can specify `chunk_size`, it eventually gets all the data:
```
    client = InfluxDBClient(host=host, port=8086, username=user, password=password, ssl=True, verify_ssl=True)
    historical_data = client.query("SELECT * FROM my_measurement;", database="processed", chunked=True, chunk_size=10000)
```
However, it takes about 5 minutes to get all the data and returns it in a very inefficient format where every point is a dictionary with the same keys as every other dictionary, as opposed to the same field for all points being contained in a single column.

Why isn't `chunk_size` an option on `DataFrameClient`'s `query()`?  

Surely I'm doing something incorrectly in my query and it's feasible to fetch these 150,000 points considerably faster than 5 minutes?

**Comment by nlejeune** [comment]
Same question here.

> Traceback (most recent call last):
>   File "export_hub_list.py", line 26, in <module>
>     rs = client.query(query)
>   File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 339, in query
>     expected_response_code=expected_response_code
>   File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 239, in request
>     timeout=self._timeout
>   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
>     r.content
>   File "/usr/lib/python2.7/site-packages/requests/models.py", line 797, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
>   File "/usr/lib/python2.7/site-packages/requests/models.py", line 722, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by xginn8** [comment]
Is this still happening? Support for chunked queries was added in the 4.1.0 release, what version of influxdb-python are you using?

**Comment by psy0rz** [comment]
Chunked support is useless the way its implemented, see #531

**Comment by nathanielatom** [comment]
@xginn8 this appears to still be happening with 5.2.2 (and influx 1.7.4). Database has 302239 rows and 148 columns, cardinality estimate 39085. Final DataFrame definitely fits into the _clients_ memory, might not all fit at once in the server's memory. I've tried chunk_sizes anywhere from 256 to 8092 and reliably get the same error. Querying for single fields seems to work relatively quickly, but `*` always gets a ChunkedEncodingError.

**Comment by nathanielatom** [comment]
I confirmed that increasing the memory of the database host server resolves the  ChunkedEncodingError.
