### ISSUE TITLE
Trouble getting tests to run

### ISSUE THREAD

**Issue by spott** [influxdata/influxdb-python#517]
When I try to run tox, I'm getting a number of similar errors to this:

```
======================================================================
ERROR: test suite for <class 'influxdb.tests.server_tests.client_test_with_server.CommonTests'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/spott/Documents/code/influxdb-python/.tox/py27/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/spott/Documents/code/influxdb-python/.tox/py27/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/spott/Documents/code/influxdb-python/.tox/py27/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/spott/Documents/code/influxdb-python/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/spott/Documents/code/influxdb-python/influxdb/tests/server_tests/base.py", line 71, in setUpClass
    _setup_influxdb_server(cls)
  File "/Users/spott/Documents/code/influxdb-python/influxdb/tests/server_tests/base.py", line 23, in _setup_influxdb_server
    udp_enabled=getattr(inst, 'influxdb_udp_enabled', False),
  File "/Users/spott/Documents/code/influxdb-python/influxdb/tests/server_tests/influxdb_instance.py", line 68, in __init__
    raise e
RuntimeError: 2017-10-17 11:37:42.895634 > influxdb prematurely exited. RC=1
stdout=
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"


stderr=[I] 2017-10-17T17:37:41Z InfluxDB starting, version v1.3.6, branch master, commit a7c3d3c0f7b74f71919047adbc4933460967a576
[I] 2017-10-17T17:37:41Z Go version go1.9, GOMAXPROCS set to 4
[I] 2017-10-17T17:37:41Z Using configuration at: /var/folders/ww/tysbq05j2cqd40gcd33197hw0000gn/T/tmpzpsIDT/influxdb.conf
run: open server: listen: listen tcp 127.0.0.1:8088: bind: address already in use

logs=u"Couldn't read logs: [Errno 2] No such file or directory: u'/var/folders/ww/tysbq05j2cqd40gcd33197hw0000gn/T/tmpzpsIDT/logs.txt'"
```

Any ideas how to fix them?  What more information is necessary to diagnose this problem?

**Comment by xginn8** [comment]
Do you have an influxdb already running on that host? `run: open server: listen: listen tcp 127.0.0.1:8088: bind: address already in use` leads me to believe there is. Also, Influxdb 1.3.6 isn't yet supported, so you'll want to make sure you're running version 1.2.4 to run the test suite.

**Comment by spott** [comment]
> so you'll want to make sure you're running version 1.2.4 to run the test suite.

How do I install 1.2.4 on a Mac?

> Also, Influxdb 1.3.6 isn't yet supported,

What is broken on 1.3.6?

**Comment by xginn8** [comment]
I'm not sure how to target 1.2.4 on Mac, though I suspect you can just build from source after checking out the correct git tag (https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md for a better idea of the details). I haven't spent much time digging yet but most admin tests fail when connecting to an InfluxDB running v1.3.6.

**Comment by xginn8** [comment]
Closing this, let us know if you're still having issues and we can reopen!
