### ISSUE TITLE
Subpath for Host - 404 Not found

### ISSUE THREAD

**Issue by darox** [influxdata/influxdb-python#569]
Im running my influxdb behind a nginx reverse proxy on port 443 with subpath /influx which is working fine with curl, but with the influxdb python library it does not. 
I get the following error back:
`Traceback (most recent call last):
  File "./check_lte_default_cell_ping_update_db.py", line 53, in <module>
    client.write_points(json_body)
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 391, in write_points
    tags=tags)
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 436, in _write_points
    expected_response_code=204
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 278, in write
    headers=headers
  File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 248, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 404: 404 page not found`

Works (curl):
`curl -i -k -XPOST 'https://192.168.1.151/write?db=mydb' -u admin:admin --data-binary 'state value=1'`

Doesn't work (python):

`client = InfluxDBClient('192.168.1.151/influx/', 443, 'admin', 'admin', 'mydb', ssl=True, verify_ssl=False)`

**Comment by micw** [comment]
It won't work this way. There's an open pull request handling this: https://github.com/influxdata/influxdb-python/pull/556

**Comment by xginn8** [comment]
Fixed in #556
