### ISSUE TITLE
InfluxDBClientError: 400 ("error":"partial write: field type conflict)

### ISSUE THREAD

**Issue by supriyopaul** [influxdata/influxdb-python#572]
**According to [influxdb doc](https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_tutorial/#data-types) :** 
" by default, InfluxDB assumes all numerical field values are floats."
```influx
> INSERT weather,location=us-midwest temperature=82 1465839830100400200
> show field keys from weather
name: weather
fieldKey    fieldType
--------    ---------
temperature float
```

**But [InfluxDBClient module for python](https://github.com/influxdata/influxdb-python):** It does not do the same. 
```python
>>> from influxdb import InfluxDBClient

>>> json_body = [{"measurement": "cpu_load_short","tags": {"host": "server01","region": "us-west"},"time": "2009-11-10T23:00:00Z","fields": {"value": 82}}]

>>> client = InfluxDBClient('localhost', 8086, 'root', 'root', 'example')
>>> client.create_database('example')
>>> client.write_points(json_body)
True
>>> 
```

```bash
[supriyo][05:59 PM][~]$ influx
Connected to http://localhost:8086 version 1.5.0
InfluxDB shell version: 1.5.0
> show databases
name: databases
name
----
_internal
logs
example
> use example
Using database example
> show measurements
name: measurements
name
----
cpu_load_short
> show field keys from cpu_load_short
name: cpu_load_short
fieldKey fieldType
-------- ---------
value    integer
> 
```
![image](https://user-images.githubusercontent.com/33823698/37906578-3d6215e2-3120-11e8-9ab3-8fdc3b6e487d.png)

**Now the concern is what if the programs change the data-types while using the InfluxdbClient?** Points won't get written into database...
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 456, in write_points
    tags=tags, protocol=protocol)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 506, in _write_points
    protocol=protocol
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 302, in write
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 263, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"value\" on 
measurement \"test\" is type integer, already exists as type float dropped=1"}

```

**Comment by ayoube01** [comment]
did  you get to solve the issues ?
thanks

**Comment by supriyopaul** [comment]
@ayoube01 after a while I realized InfluxDBClient is doing the expected thing. It conveys python datatypes to influxDB without any intelligent decision making of assumptions.

**Comment by tux-00** [comment]
@ayoube01 @supriyopaul the temporary solution I used:
```python
def df_int_to_float(df):
    for i in df.select_dtypes('int').columns.values:
        df[i] = df[i].astype(float)
    return df

df = self.df_int_to_float(df)
```

**Comment by supriyopaul** [comment]
@tux-00 Thanks, I too did the same.

**Comment by zsyh** [comment]
import influxdb
from influxdb import InfluxDBClient
from influxdb.line_protocol import _get_unicode, quote_ident, _is_float, text_type


class MyInfluxDBClient(InfluxDBClient):
    def __init__(self, host='localhost', port=8086, username='root', password='root', database=None, ssl=False,
                 verify_ssl=False, timeout=None, retries=3, use_udp=False, udp_port=4444, proxies=None, pool_size=10,
                 path=''):
        super().__init__(host, port, username, password, database, ssl, verify_ssl, timeout, retries, use_udp, udp_port,
                         proxies, pool_size, path)

        # monkey patch, no integer
        def _escape_value(value):
            value = _get_unicode(value)

            if isinstance(value, text_type) and value != '':
                return quote_ident(value)
            elif _is_float(value):
                return repr(value)

            return str(value)
        influxdb.line_protocol._escape_value = _escape_value

**Comment by webmaniak** [comment]
In the end, shouldn't the Python module do the conversion itself?

I mean, if by default InfluxDB considers all `int` values to be `float` (unless told explicitely with the "i" character placed after the `int`value), then why both `InfluxDbClient` and its subclasses do not enforce this rule automatically by converting values like @tux-00 suggested?
