### ISSUE TITLE
Write PandasDataframe to InfluxDb

### ISSUE THREAD

**Issue by chappi6** [influxdata/influxdb-python#607]
Hi 

I try to insert data from an array to influxdb. 
I found the Pandas framework wicht should work really nice for that. I started my self with some demo code from the influx docs, but it didnt work. 
Any ideas whats wrong? 

```
    client = InfluxDBClient(host, port, user, password, dbname)
    t = time.strftime('%Y-%m-%d %H:%M:%S')
    headers = ['time','tag1','tag2','field1','field2']
    data 	= [[t,'MSFT','NYSE',1.3,2.5],[t,'APPL','NYSE',3.5,4.24]]
    df 		= pd.DataFrame(data, columns = headers)
    df['time'] = pd.to_datetime(df['time'])
    df 		= df.set_index('time')
    tags 		= { 'tag1': df[['tag1']], 'tag2': df[['tag2']]  }
    print(df.head())
    client.write_points(df, 'demo',
                        {'k1': 'v1', 'k2': 'v2'}, protocol='json')``
```
Return Code is: 

Traceback (most recent call last):
  File "/home/schappi/Schreibtisch/intelmq-master/influx/main.py", line 25, in <module>
    {'k1': 'v1', 'k2': 'v2'}, protocol='json')
  File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 483, in write_points
    tags=tags, protocol=protocol)
  File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 545, in _write_points
    protocol=protocol
  File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 315, in write
    data = make_lines(data, precision).encode('utf-8')
  File "/usr/local/lib/python3.4/dist-packages/influxdb/line_protocol.py", line 132, in make_lines
    point.get('measurement', data.get('measurement'))))
AttributeError: 'str' object has no attribute 'get'

**Comment by xginn8** [comment]
If you want to write a dataframe, you should use the `DataFrameClient` constructor rather than the `InfluxDBClient` constructor. See: https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_pandas.py
