### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by stef30360** [influxdata/influxdb-python#609]
Hi, 
When I run 
`client1 = DataFrameClient(host1, port, user, password, dbname1)
......
response = client1.query(query)`
I've an error "Max retries exceeded with url". I think that it's a max query API, but how can I solve this bug ?
regards .
stef

**Comment by xginn8** [comment]
Can you paste a full stacktrace please?

**Comment by stef30360** [comment]
HI 
I don't understand, now it works ! sorry.

**Comment by keivanK1** [comment]
I got same error.
Traceback:
`Traceback (most recent call last):
  File "influxdb-1.py", line 7, in <module>
    client.create_database('test')
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 579, in create_database
    method="POST")
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 416, in query
    expected_response_code=expected_response_code
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 267, in request
    timeout=self._timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22test%22(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7856cd9f90>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by AdiYElisha** [comment]
I have the exact same problem

**Comment by ibnipun10** [comment]
I am suffering from the same problem
