### ISSUE TITLE
influxdb-python 5.2.0: Query with UTF-8 chars causes exception

### ISSUE THREAD

**Issue by mattibf** [influxdata/influxdb-python#633]
Hello,

We observed a behavior change when moving from influxdb-python from 5.1.0 to 5.2.0.
A query containing non-ASCII UTF-8 characters was successfully executed with 5.1.0, but fails with 5.2.0.

Sample code:

-----------------------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from influxdb import InfluxDBClient

client = InfluxDBClient('localhost', 8086, 'user', 'pwd', 'test')

queryStr = 'SELECT value, value_meta FROM test.default_test."tempest-ｎａｍｅ-110197974"'
result = client.query(queryStr)
-----------------------------------------------------------------------------------------

Pls. note: The strange looking "ｎａｍｅ" are UTF-8 characters used for testing.
Hex representaion: EFBD8E, EFBD81, EFBD8D, EFBD85

With influxdb-python, version=5.1.0, the query works without problems
With influxdb-python, version=5.2.0, the query causes an exception:
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "influxdb-client-issue.py", line 12, in <module>
    result = client.query(queryStr)
  File "/home/bandorf/.local/lib/python2.7/site-packages/influxdb/client.py", line 408, in query
    if query.lower().startswith("select ") and " into " in query.lower():
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 55: ordinal not in range(128)
-----------------------------------------------------------------------

Now, I've got the following questions:
- Was this an intentional behavior change?
  As of now, I consider this a bug.
- Is there any work-around?

Thanks,
Matthias

**Comment by xginn8** [comment]
@mattibf this bug is a result of https://github.com/influxdata/influxdb-python/blob/master/CHANGELOG.md#changed-1, specifically: 
`Update POST/GET requests to follow verb guidelines from InfluxDB documentation`.

I will PR a fix in the next day or so, thanks for reporting this bug!

**Comment by witekest** [comment]
Any update on this? The bug is still present in version 5.2.1

**Comment by witekest** [comment]
The issue still exists in version 5.2.2.
It affects only Python 2 code. I could confirm that the client works nicely with Python 3.

**Comment by witekest** [comment]
The issue still exists in 5.2.3.

**Comment by aviau** [comment]
Please don't post after every release. We will close this issue when it is fixed.
