### ISSUE TITLE
write_points does not write data 

### ISSUE THREAD

**Issue by zhaodaozi** [influxdata/influxdb-python#654]
when i use influxdb0.8.8 and influxdb.influxdb0.8 package, i realized my data not save in influxdb0.8.8 database, i was hoping someone would help me this error was, will next my code.

**Comment by zhaodaozi** [comment]
from influxdb.influxdb08 import InfluxDBClient

def cpu_log_save_influxdb():
    json_body = [
        {
            "measurement": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "time": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
    client = InfluxDBClient('localhost', 8086, 'root', 'root', 'mydb')
    client.write_points(json_body)
    result = client.query('select value from cpu_load_short;')
    print("Result: {0}".format(result))

cpu_log_save_influxdb()

**Comment by zhaodaozi** [comment]
json_body = [
        {
            "measurement": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "time": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
    client = InfluxDBClient('localhost', 8086, 'root', 'root', 'mydb')
    client.write_points(json_body)
    result = client.query('select value from cpu_load_short;')
    print("Result: {0}".format(result))

**Comment by zhaodaozi** [comment]
this is my error
[root@localhost ~]# /opt/manager/env/bin/python test.py 
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    cpu_log_save_influxdb()
  File "test.py", line 19, in cpu_log_save_influxdb
    result = client.query('select value from cpu_load_short;')
  File "/opt/manager/env/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 423, in query
    chunked=chunked)
  File "/opt/manager/env/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 451, in _query
    expected_response_code=200
  File "/opt/manager/env/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 248, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.influxdb08.client.InfluxDBClientError: 400: Couldn't find series: cpu_load_short

**Comment by zhaodaozi** [comment]
I think I've found the answer to my question, My json is not in the right format, and the 0.8.8 version of influxdb should be:
    json_body = [
      {
        "name" : "memory_message",
        "columns" : ["memory_total", "memory_free", "memory_used"],
        "points" : [
          [memory_total, memory_free, memory_used]
        ]
      }
    ]

**Comment by zhaodaozi** [comment]
I think I've found the answer to my question, My json is not in the right format, and the 0.8.8 version of influxdb should be:
    json_body = [
      {
        "name" : "memory_message",
        "columns" : ["memory_total", "memory_free", "memory_used"],
        "points" : [
          [memory_total, memory_free, memory_used]
        ]
      }
    ]
