### ISSUE TITLE
Network Issue

### ISSUE THREAD

**Issue by syedsrepo** [influxdata/influxdb-python#703]
Hi,

I am trying to connect to my local InfluxDB instance and execute a query, there is no issue in connecting from linux shell, but I get an Network Issue error while using DataFrameClient

# cat influx.py

from influxdb import DataFrameClient

query = "select * from cpufreq_value limit 10"
client = DataFrameClient(host='localhost', database='collectd', port='8086')
rs = client.query(query)
dict = list(rs.get_points('cpufreq_value'))

# python influx.py
Traceback (most recent call last):
  File "influx.py", line 6, in <module>
    rs = client.query(query)
  File "/opt/anaconda3/lib/python3.7/site-packages/influxdb/_dataframe_client.py", line 182, in query
    results = super(DataFrameClient, self).query(query, **query_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/influxdb/client.py", line 416, in query
    expected_response_code=expected_response_code
  File "/opt/anaconda3/lib/python3.7/site-packages/influxdb/client.py", line 282, in request
    raise InfluxDBServerError(response.content)
influxdb.exceptions.InfluxDBServerError: b'<HTML><HEAD>\r\n<TITLE>Network Error</TITLE>\r\n</HEAD>\r\n<BODY>\r\n<FONT face="Helvetica">\r\n<big><strong></strong></big><BR>\r\n</FONT>\r\n<blockquote>\r\n<TABLE border=0 cellPadding=1 width="80%">\r\n<TR><TD>\r\n<FONT face="Helvetica">\r\n<big>Network Error (tcp_error)</big>\r\n<BR>\r\n<BR>\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face="Helvetica">\r\nA communication error occurred: "Connection refused"\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face="Helvetica">\r\nThe Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face="Helvetica" SIZE=2>\r\n<BR>\r\nFor assistance, contact your network support team.\r\n</FONT>\r\n</TD></TR>\r\n</TABLE>\r\n</blockquote>\r\n</FONT>\r\n</BODY></HTML>\r\n'

# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 1.6.5
InfluxDB shell version: 1.1.1
>

# python -V
Python 3.7.1

Kindly help me with this issue please

**Comment by arieldf** [comment]
@syedsrepo Getting the same error and symptoms. Did you find a solution to this? Best, Ariel
