### ISSUE TITLE
KeyError: 'points' when trying to insert

### ISSUE THREAD

**Issue by SiegelDaniel** [influxdata/influxdb-python#727]
Hello everyone, I have the following codesnippet that I wrote according to the documentation [here](https://influxdb-python.readthedocs.io/en/latest/api-documentation.html)

`
```
from InfluxDB import InfluxDBClient

class testAdapter():


    def __init__(self):
        self.client = InfluxDBClient(host='testhost.test',port=8086)
        self.client.switch_database('Traces')
    
    def create_json_dict(self,timestamp,data,processname,measurement):
            '''Creates a json style dict as a datapoint to be inserted'''
            tags   = {'processname':processname}
            fields = {'systemcall':data}
            body   = {'measurement':measurement,
                      'tags':tags,
                      'time':timestamp,
                      'fields':fields}
            return body
            
    def insert(self,datapoints):
            print(type(datapoints))
            print(datapoints)
            if self.client.write(datapoints,protocol = 'json') == True:
                print("Inserted datapoints {0}".format(datapoints))         
            else:
                print("Something went wrong")
            
                
if __name__ == "__main__":
    adapter = testAdapter()
    nuggi = adapter.insert(adapter.create_json_dict("2019-06-26T12:38:43+02:00","TEST","TESTPROC","Traces"))
```

On execution I get:
```

<class 'dict'>
{'measurement': 'Traces', 'tags': {'processname': 'TESTPROC'}, 'time': '2019-06-26T12:38:43+02:00', 'fields': {'systemcall': 'TEST'}}
Traceback (most recent call last):
  File "influxtest.py", line 33, in <module>
    nuggi = adapter.insert(adapter.create_json_dict("2019-06-26T12:38:43+02:00","TEST","TESTPROC","Traces"))
  File "influxtest.py", line 25, in insert
    if self.client.write(datapoints,protocol = 'json') == True:
  File "C:\Users\Siegel\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb\client.py", line 315, in write
    data = make_lines(data, precision).encode('utf-8')
  File "C:\Users\Siegel\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb\line_protocol.py", line 127, in make_lines
    for point in data['points']:
KeyError: 'points'


```
What is the problem here?

**Comment by SiegelDaniel** [comment]
I think I fixed that by creating a dict called points in which I inserted the datapoint.
However, when I send this, I get:
```
<class 'dict'>
{'points': [{'measurement': 'Traces', 'tags': {'processname': 'TESTPROC'}, 'time': '2019-06-26T12:38:43+02:00', 'fields': {'systemcall': 'TEST'}}]}
Traceback (most recent call last):
  File "influxtest.py", line 32, in <module>
    adapter.insert(adapter.create_json_dict("2019-06-26T12:38:43+02:00","TEST","TESTPROC","Traces"))
  File "influxtest.py", line 24, in insert
    if self.client.write(datapoints,protocol = 'json') == True:
  File "C:\Users\Siegel\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb\client.py", line 327, in write
    headers=headers
  File "C:\Users\Siegel\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb\client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"database is required"}
```

**Comment by shantanoo-desai** [comment]
Like in the documentation you need to mention the database name:

    client = InfluxDBClient(host='127.0.0.1', port=8086, database='dbname')

**Comment by SiegelDaniel** [comment]
Oops, forgot that. Thank you.
