### ISSUE TITLE
influxdb.exceptions.InfluxDBClientError: 403:

### ISSUE THREAD

**Issue by lladhibhutall** [influxdata/influxdb-python#728]
```
client.create_database('example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Downloads\python-3.7.3-embed-amd64\lib\site-packages\influxdb\client.py", line 579, in create_database
    method="POST")
  File "C:\Users\Downloads\python-3.7.3-embed-amd64\lib\site-packages\influxdb\client.py", line 416, in query
    expected_response_code=expected_response_code
  File "C:\Users\Downloads\python-3.7.3-embed-amd64\lib\site-packages\influxdb\client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 403:
```

Getting this error while running even the basic example given in the readme.

Platform- Windows 10
InfluxDB Version- 1.7.6

**Comment by lovasoa** [comment]
This does not seem to be an issue with influxdb-client itself, but rather a configuration issue. 
@lladhibhutall Can you query the database with curl ? what connection parameters do you use ?
@aviau This issue might be worth closing, or at least marked as *needinfo*.

**Comment by aviau** [comment]
>but rather a configuration issue

Yeah. Support shouldn't be handled here.
