### ISSUE TITLE
InfluxDBClient.ping() method return 200:OK, not expected_response_code=204.

### ISSUE THREAD

**Issue by JFRabbit** [influxdata/influxdb-python#777]
- **InfluxDB version:** 1.7.6
- **InfluxDB-python version:** influxdb==5.2.3
- **Python version:** 3.7.1
- **Operating system version:** macOS 10.15.2

### How to reproduce:
test code:
```
from influxdb import InfluxDBClient

config = {
        'host':     'influxdb.xxx.com',
        'port':     80,
        'database': 'foobar'

    }

client = InfluxDBClient(**config)

res = client.query('SHOW DATABASES')

print(res)

client.ping()
```

console log:
```
ResultSet({'('databases', None)': [{'name': '_internal'}, {'name': 'default'}, {'name': 'foobar'}]})
Traceback (most recent call last):
  File "/Users/jasonzhang/Documents/code/foobar/foo1.py", line 25, in <module>
    print(client.ping())
  File "/Users/jasonzhang/Documents/code/foobar/venv/lib/python3.7/site-packages/influxdb/client.py", line 540, in ping
    expected_response_code=204
  File "/Users/jasonzhang/Documents/code/foobar/venv/lib/python3.7/site-packages/influxdb/client.py", line 302, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 200: OK
```

I got 200:OK, but the ping method expect to get 204.

**Comment by russorat** [comment]
@JFRabbit thank you for the issue. I'm wondering if you have a proxy between you and influxdb which is returning that response code. I just tried on influxdb 1.7.9 and it returns a `204` as a response, not a 200.

```
➜  ~ curl -v localhost:8086/ping
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8086 (#0)
> GET /ping HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 204 No Content
< Content-Type: application/json
< Request-Id: 358ec672-3ca3-11ea-85fb-8c85907aa7fb
< X-Influxdb-Build: OSS
< X-Influxdb-Version: v1.7.9
< X-Request-Id: 358ec672-3ca3-11ea-85fb-8c85907aa7fb
< Date: Tue, 21 Jan 2020 23:10:26 GMT
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

**Comment by JFRabbit** [comment]
thanks,  maybe caused by k8s traefik
