### ISSUE TITLE
issue exporting to influxdb

### ISSUE THREAD

**Issue by roborick** [influxdata/influxdb-python#874]
- **InfluxDB version:** e.g. 1.7.7 (output of the `influx version` command)
- **InfluxDB-python version:** e.g. 5.2.2 (output of the `python -c "from __future__ import print_function; import influxdb; print(influxdb.__version__)"` command)
- **Python version:** e.g. 3.7.4 (output of the `python --version` command)
- **Operating system version: Ubuntu 18.04

when running the command glances --export influxdb

I get this error:
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 51, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 48, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 103, in load_modules
    self.load_exports(args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 178, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_influxdb.py", line 27, in <module>
    from influxdb import InfluxDBClient
ImportError: No module named influxdb

I do have influxdb installed as I'm using varken

**Comment by robisa693** [comment]
Hi, in your error you can see that glances is installed to "/usr/local/lib/**python2.7**/dist-packages/glances/stats.py.
Since glances can be installed on python 2.7 aswell im guessing maybe that's your problem. Double check that your pip is installing to the correct python version environment or maybe try using pip3 install x.
